### ISSUE TITLE
xlib panic 

### ISSUE THREAD

**Issue by dkxb** [Mendess2526/rust-pacman#1]
Thanks for the code. I can cargo build but it seems that xlib panics as soon as I launch the program. 
Here is the error message:
thread 'main' panicked at 'attempted to leave type `std::mem::ManuallyDrop<xlib::Xlib>` uninitialized, which is invalid', /home/madoka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:671:9

Is this an xlib bug? My OS is manjaro.

**Comment by mendess** [comment]
Thank you for the bug report. I bumped all the dependencies to the latest version and it seems to be working now. It's probably an xlib bug yes.

Also this code is probably not very good :smile: the dependencies were weird, I knew a lot less rust back then. Get inspired at your own peril :stuck_out_tongue:
